#!/bin/sh

case "$(file -Lb --mime-type -- "$1")" in
image/*)
  # chafa -f sixel -s "$2x$3" --animate off --polite on "$1"
  chafa -s "$2x$3" --animate off --polite on "$1"
  exit 1
  ;;
text/*)
  bat --color=always --style=plain "$1"
  ;;
application/javascript | application/json)
  bat --color=always --style=plain "$1"
  ;;
*)
  exiftool "$1" | bat --color=always --style=plain -l nix
  ;;
esac
