#!/bin/sh
case "$(file -Lb --mime-type -- "$1")" in
image/*)
  # chafa -f sixel -s "$2x$3" --animate off --polite on "$1"
  chafa -s "$2x$3" --animate off --polite on "$1"
  exit 1
  ;;
text/*)
  bat --color=always --style=plain "$1"
  ;;
application/javascript)
  bat --color=always --style=plain "$1"
  ;;
esac
