unbind f
unbind p
unbind t
unbind ;p
bind q hint
bind t fillcmdline tabopen -w
bind pp fillcmdline winopen -private
bind ;p hint -wp
unbindurl ^https?://.*youtube\.com >>
unbindurl ^https?://.*youtube\.com <<
unbindurl ^https?://.*youtube\.com .



# for idea
current_url winopen -private
